---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "melt_delgeno"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::melt=1.0.3"
